package snappy.pack;

public interface IMapperStats {
    /// <summary>
    /// Number of times the mapper tried to create a sprite, but failed to do so.
    /// For example, if it uses a canvas with a certain size, the canvas may have been too small
    /// to place all images.
    /// </summary>
    int getCandidateSpriteFails();
    void setCandidateSpriteFails(int candidateSpriteFails);

    /// <summary>
    /// Number of candidate sprites successfully generated by the mapper.
    /// A mapper would return only the best of the candidate sprites from its Mapping method.
    /// </summary>
    int getCandidateSpritesGenerated();
    void setCandidateSpritesGenerated(int candidateSpritesGenerated);

    /// <summary>
    /// Number of times an attempt was made to add an image to the canvas used by the mapper.
    /// </summary>
    int getCanvasRectangleAddAttempts();
    void setCanvasRectangleAddAttempts( int canvasRectangleAddAttempts );

    /// <summary>
    /// Number of cells generated by the canvas used by the mapper.
    /// </summary>
    int getCanvasNbrCellsGenerated();
    void setCanvasNbrCellsGenerated( int canvasNbrCellsGenerated );
}
